#!/bin/bash
./Cleanall
cp -r 0.org 0

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="waveFoam"

# Create the computational mesh
runApplication blockMesh

# Create the wave probes
runApplication waveGaugesNProbes

# Compute the wave parameters
runApplication setWaveParameters

# Write the relaxation zone layout
runApplication relaxationZoneLayout

# Set the wave field
runApplication setWaveField

# rm -rf processor*
# decomposePar -force ; mpirun -np 16 waveFoam -parallel
# reconstructPar

# Run the application
runApplication $application

# To a post-processing analysis
#runApplication postProcessWaves2Foam
